POST http://localhost:3000/login
Content-Type: application/json

{
  "email": "john@gmail.com",
  "password": "pass1"
}

##################Employee##################
### Create Employee
POST http://localhost:3000/employee/add
Content-Type: application/json

{
  "emp_id": "EMP002",
  "name": "Aekankshi",
  "email": "demo@gmail.com",
  "password": "demo1",
  "role": "employee",
  "doj": "2025-05-10",
  "department_id": 2,
  "primary_skill_id": 2,
  "secondary_skill_id": 3
}

### Get Employee by ID
GET http://localhost:3000/employee/EMP001
Accept: application/json

### Get Employee
GET http://localhost:3000/employee
Accept: application/json

### Update Employee
PUT http://localhost:3000/employee/EMP001
Content-Type: application/json

{
  "name": "John Smith",
  "email": "john.smith@example.com",
  "role": "Senior Developer"
}

### Delete Employee
DELETE http://localhost:3000/employee/deleteemp/EMP001
Accept: application/json

### Restore Employee
PATCH http://localhost:3000/employee/EMP001/restore
Accept: application/json


##################Skill##################
###fetch all skills
GET http://localhost:3000/skill
Accept: application/json

###add new skill
POST http://localhost:3000/skill/add
Content-Type: application/json

{
  "name": "Nodejs",
  "category_id": 2
}


##################Skill##################
###fetch all categories
GET http://localhost:3000/category
Accept: application/json

###add new skill
POST http://localhost:3000/category/add
Content-Type: application/json

{
  "name": "Cloud-AWS"
}


##################Department##################
###fetch all categories
GET http://localhost:3000/dept
Accept: application/json

###add new skill
POST http://localhost:3000/dept/add
Content-Type: application/json

{
  "name": "IT-Infrastructure"
}

###Update status
PUT http://localhost:3000/update-status
Content-Type: application/json

{
  "EmployeeId": "EMP001",
  "TrainingId": 1,
  "completionstatus": "Completed"
}
