###get Employee
GET http://localhost:3000/employees/
//Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbXBfaWQiOiJFTVAwMiIsInJvbGUiOiJBZG1pbiIsImlhdCI6MTc0NTkwNzU3MCwiZXhwIjoxNzQ1OTkzOTcwfQ.9NO0Pw1Y3urqObLaWseWXQbr3YM_c7cVTkM7FCmsDXM

###get employeeByid
GET http://localhost:3000/employees/EMP01
//Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbXBfaWQiOiJFTVAwMSIsInJvbGUiOiJFbXBsb3llZSIsImlhdCI6MTc0NTkwODU1MiwiZXhwIjoxNzQ1OTk0OTUyfQ.dtLO5KpAb9yFtxQNClbENF8Xv9xpFpgRzt2sCwRg0uQ

###get Employee by role
GET http://localhost:3000/employees/filter?role=Admin
Content-Type:  application/json


###Add employee
POST http://localhost:3000/auth/register
//Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbXBfaWQiOiJFTVAwMSIsInJvbGUiOiJFbXBsb3llZSIsImlhdCI6MTc0NjUxMDYzNiwiZXhwIjoxNzQ2NTk3MDM2fQ.nqyteL-n74NytoiE7fRUE8x1U4wNzKjnRD1oEXUdUP0
Content-Type: application/json

{
  "emp_id": "EMP02",
  "name": "Sharvary",
  "email": "sharvary@gmail.com",
  "password": "sharvary",
  "date_of_joining": "2025-01-13",
  "department_name": "IT-QA",
  "skill_category": "Backend",
  "skill": "Nodejs",
  "skill_level": "Intermediate",
  "role": "Admin",
  "status": "Completed"
}

###Login
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "email": "snehal@gmail.com",
  "password": "snehal"
}

###reset password
POST http://localhost:3000/auth/reset-password
//Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbXBfaWQiOiJFTVAwMSIsInJvbGUiOiJFbXBsb3llZSIsImlhdCI6MTc0NTkwODkzNSwiZXhwIjoxNzQ1OTk1MzM1fQ.OySTVqdEfplGpd77eLXB8WVI8X0gE9UKA1WUqNHDFv0
Content-Type: application/json

{
  "email": "bob@gmail.com",
  "newPassword": "bob123",
  "confirmPassword":"bob123"
}



###edit employee
PUT http://localhost:3000/employees/editemp/EMP01
//Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbXBfaWQiOiJFTVAwMSIsInJvbGUiOiJFbXBsb3llZSIsImlhdCI6MTc0NTkwNzgxNSwiZXhwIjoxNzQ1OTk0MjE1fQ._2KYjsyL2wesNU2NEAdzGphLtM5InaOdcLaS_aHZ3EY
Content-Type: application/json

{
  "department_name": "IT-Application",
  "skill_category": "Frontend",
  "skill": "React",
  "skill_level": "Intermediate"
}

###edit status
PUT http://localhost:3000/employees/status/EMP01
Content-Type: application/json

{
  "status": "Completed"
}

###delete employee
DELETE http://localhost:3000/employees/delemp/EMP001

###distinct skills
GET http://localhost:3000/employees/skills

###audit record
GET http://localhost:3000/employees/audit
//Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbXBfaWQiOiJFTVAwMSIsInJvbGUiOiJFbXBsb3llZSIsImlhdCI6MTc0NjUxMDYzNiwiZXhwIjoxNzQ2NTk3MDM2fQ.nqyteL-n74NytoiE7fRUE8x1U4wNzKjnRD1oEXUdUP0


# ###add audit record
# POST http://localhost:3000/audit
# Content-Type: application/json

# {
#   "emp_id": "EMP001",
#   "field_changed": "skill_level",
#   "old_value": "Beginner",
#   "new_value": "Intermediate",
#   "changed_by": "admin",
#   "description": "Updated skill level from Beginner to Intermediate"
# }
