###get Employee
GET http://localhost:3000/employees/

###get Employee by role
GET http://localhost:3000/employees/role

###get employeeByid
GET http://localhost:3000/employees/EMP01
//Authorization: Bearer <eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbXBfaWQiOiJFTVAwMSIsInJvbGUiOiJFbXBsb3llZSIsImlhdCI6MTc0NTMxNzIyNywiZXhwIjoxNzQ1NDAzNjI3fQ.dJ9d0CTk5sPHpkA5FLk0Q6J5GigQCIGY0jh9MNj2Lmg>

###Add employee
POST http://localhost:3000/auth/register
Content-Type: application/json

{
  "emp_id": "EMP02",
  "name": "Sharvary",
  "email": "sharvary@gmail.com",
  "password": "sharvary",
  "date_of_joining": "2025-01-13",
  "department_name": "IT-QA",
  "skill_category": "Backend",
  "skill": "Nodejs",
  "skill_level": "Intermediate",
  "role": "Admin",
  "status": "Completed"
}

###Login
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "email": "snehal@gmail.com",
  "password": "snehal"
}

###reset password
POST http://localhost:3000/auth/reset-password
Content-Type: application/json

{
  "email": "bob@gmail.com",
  "newPassword": "bob123",
  "confirmPassword":"bob123"
}



###edit employee
PUT http://localhost:3000/employees/editemp/EMP01
Content-Type: application/json

{
  "department_name": "IT-Application",
  "skill_category": "Frontend",
  "skill": "React",
  "skill_level": "Intermediate"
}

###edit status
PUT http://localhost:3000/employees/status/EMP01
Content-Type: application/json

{
  "status": "Completed"
}

###delete employee
DELETE http://localhost:3000/employees/delemp/EMP001

###add audit record
POST http://localhost:3000/audit
Content-Type: application/json

{
  "emp_id": "EMP001",
  "field_changed": "skill_level",
  "old_value": "Beginner",
  "new_value": "Intermediate",
  "changed_by": "admin",
  "description": "Updated skill level from Beginner to Intermediate"
}

###distinct skills
GET http://localhost:3000/employees/skills